# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "random6@email.com",
  "name": "Jack",
  "password": "password",
  "isPro": false,
  "image": "image.jpg"
}

###

# Пользователи
## Аутентификация пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "random6111@email.com",
  "password": "4a83854cf6f0112b4295bddd535a9b3fbe54a3f90e853b59d42e4bed553c55a4"
}

###

# Пользователи
## Получить избранные объявления пользователя

GET http://localhost:4000/users/favorites/67cc69f382993a06c96149af HTTP/1.1
Content-Type: application/json

###

# Пользователи
## Добавить объявление в избранное

PUT http://localhost:4000/users/favorites/67cc7a6b9184292994085e52/offers/67cddf3ff4d66b3437c85154 HTTP/1.1
Content-Type: application/json

{ "isAdding": true }

###


# Пользователи
## Удалить объявление из избранного

PUT http://localhost:4000/users/favorites/67cc7a6b9184292994085e52/offers/67cddf3ff4d66b3437c85154 HTTP/1.1
Content-Type: application/json

{ "isAdding": false }

###


## Отправить изображение

POST http://localhost:4000/users/67cc69f382993a06c96149af/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="test.png"
Content-Type: image/png

< /Users/kirill.k/Desktop/test.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
