# Предложения по аренде
## Получить список предложений по аренде
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###


## Добавить новое предложение по аренде
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Второй Договор аренды торговой площади",
  "description": "Второй Контракт на аренду квартиры для проживания",
  "city": "Paris",
  "preview": "shining.jpg",
  "images": [
    "category-book.jpg,category-disk.jpg,category-home.jpg,category-games.jpg,category-entertainment.jpg,category-films.jpg"
  ],
  "premium": true,
  "housingType": "Apartment",
  "roomsNumber": 3,
  "guestsNumber": 2,
  "rentPrice": 55555,
  "comforts": [
    "Towels"
  ],
  "coordinates": [
    12.7,
    -40.1
  ],
  "userId": "67cc6fa58b5ca7d906c2138b",
  "createdAt": "2025-03-08T16:01:55.531Z",
  "commentsNumber": 0,
  "rating": null,
  "isFavorite": false
}

###

# Детальное предложение по аренде
## Получить детальное предложение по аренде
GET http://localhost:4000/offers/67cc69f382993a06c96149b2 HTTP/1.1
Content-Type: application/json

###


# Обновления данных в предложении по аренде
## Обновить данные в предложение по аренде

PUT http://localhost:4000/offers/67cc69f382993a06c96149b2 HTTP/1.1
Content-Type: application/json

{
  "title": "New title name",
  "description": "Второй Контракт на аренду квартиры для проживания",
  "city": "Paris",
  "preview": "shining.jpg",
  "images": [
    "category-book.jpg,category-disk.jpg,category-home.jpg,category-games.jpg,category-entertainment.jpg,category-films.jpg"
  ],
  "premium": true,
  "housingType": "Apartment",
  "roomsNumber": 3,
  "guestsNumber": 2,
  "rentPrice": 55555,
  "comforts": [
    "Towels"
  ],
  "coordinates": [
    12.7,
    -40.1
  ],
  "userId": "67cc6fa58b5ca7d906c2138b",
  "createdAt": "2025-03-08T16:01:55.531Z",
  "commentsNumber": 0,
  "rating": null,
  "isFavorite": false
}

###

# Получение премиального предложения по аренде
## Получить премиальное предложение по аренде
GET  http://localhost:4000/offers/premium/Paris HTTP/1.1
Content-Type: application/json

###
